name: MLflow Pipelines Example Tests

on:
  push:
    branches:
      - main
      - branch-[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
      - branch-[0-9]+.[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_number || github.ref }}
  cancel-in-progress: true

# Use `bash --noprofile --norc -exo pipefail` by default for all `run` steps in this workflow:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

env:
  # Note miniconda is pre-installed in the virtual environments for GitHub Actions:
  # https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/miniconda.sh
  MLFLOW_CONDA_HOME: /usr/share/miniconda

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./.github/actions/setup-python
      with:
        python-version: "3.7"
    - uses: ./.github/actions/cache-pip
    - name: Add problem matchers
      run: |
        echo "::add-matcher::.github/workflows/matchers/pylint.json"
    - name: Install dependencies
      run: |
        pip install -r .github/workflows/scripts/lint-requirements.txt
    - name: Run lint checks
      run: |
        .github/workflows/scripts/lint.sh

  sklearn_regression_pipelines:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.7"
      - name: Install dependencies
        env:
          INSTALL_SKLEARN_PIPELINE_DEPS: true
        run: |
          source ./.github/workflows/scripts/install-common-deps.sh
          pip install -r .github/workflows/scripts/test-requirements.txt
      - name: Run tests
        run: |
          export MLFLOW_PIPELINE_EXAMPLE=$(pwd)
          pytest sklearn_regression/tests

  sklearn_regression_pipelines-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.7"
      - name: Install dependencies
        env:
          INSTALL_SKLEARN_PIPELINE_DEPS: true
        run: |
          pip install -e .
          pip install -r sklearn_regression/requirements.txt
          pip install -r .github/workflows/scripts/test-requirements.txt
      - name: Run tests
        run: |
          export MLFLOW_PIPELINE_EXAMPLE=$(pwd)
          pytest sklearn_regression/tests
