name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt 
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint ./steps --fail-under=6
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt 
        pip install pytest
    - name: Analysing the code with pylint
      run: |
        pytest
  integration-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run a databricks notebook
      uses: databricks/run-notebook@v0
      with:
       local-notebook-path: .github/integration_test/notebook.py
       databricks-host: https://e2-dogfood.staging.cloud.databricks.com
       databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
       git-commit: ${{ github.sha }}
       existing-cluster-id: "1118-013127-82wynr8t"
